### ISSUE TITLE
Behöver loggan

### ISSUE THREAD

**Issue by reelode** [chas-academy/u02-redesign-a-team#6]
Hej några från teamet,

Jag behöver **loggan** som ni designat.
Bestämde vi en färg för boxen i loggan?

Ciao, Simon

**Comment by pernilla-hallgren** [comment]
Hej! Jag är inte hemma just nu men jag tog bara loggan från hemsidan och
gjorde om den i figma med mörkblå färgen och Roboto font :) Kan skicka den
senare i eftermiddag om du vill?

//Pernilla

**Comment by reelode** [comment]
Hej Pernilla,
Jag löste det, tack för snabb återkoppling. (ville bara prova issues)
//Simon

**Comment by pernilla-hallgren** [comment]
Vad bra! Inga problem :)
